name: "Markdown to Notion"
description: "Syncs Markdown files to Notion pages and updates an index block."

inputs:
  notion_token:
    description: "Notion Integration Secret"
    required: true

  docs_folder:
    description: "Path to folder containing markdown files"
    required: false
    default: "docs"

  notion_mapping_file:
    description: "Path to the markdown table used to store notion_page_id mappings (default: <docs_folder>/_notion_links.md)"
    required: false

  page_block_id:
    description: "Anchor block ID/URL used to insert page shortcut links after this block"
    required: false

  page_id:
    description: "Notion page ID where files will be created when page_block_id is not provided"
    required: false

  title_prefix_separator:
    description: "Separator for title_prefix folder paths"
    required: false
    default: "→"

  commit_strategy:
    description: "How to persist notion_page_id updates: 'push', 'pr' (default), or 'none'"
    required: false
    default: "pr"

  pr_branch_prefix:
    description: "Prefix for the PR branch when commit_strategy=pr"
    required: false
    default: "auto-notion-sync/"

  github_token:
    description: "GitHub token used to push commits or open PRs for notion_page_id updates"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Sync markdown to Notion
      run: npx tsx src/main.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_NOTION_TOKEN: ${{ inputs.notion_token }}
        INPUT_DOCS_FOLDER: ${{ inputs.docs_folder }}
        INPUT_NOTION_MAPPING_FILE: ${{ inputs.notion_mapping_file }}
        INPUT_PAGE_BLOCK_ID: ${{ inputs.page_block_id }}
        INPUT_PAGE_ID: ${{ inputs.page_id }}
        INPUT_TITLE_PREFIX_SEPARATOR: ${{ inputs.title_prefix_separator }}
        INPUT_COMMIT_STRATEGY: ${{ inputs.commit_strategy }}
        INPUT_PR_BRANCH_PREFIX: ${{ inputs.pr_branch_prefix }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
